-- premake5.lua

workspace "alica"
   configurations { "Debug", "Release" }
   postbuildmessage "Copying dependencies..."
 --  postbuildcommands { "cp -R grid_sim/textures  bin/%{cfg.buildcfg}" }
   

project "alica"
   kind "SharedLib"
   language "C++"
   cppdialect "C++14"
   targetdir "bin/%{cfg.buildcfg}"

   -- libdirs { 
   --  os.findlib("alica_common_config"), 
   --  os.findlib("alica_solver_interface"), 
   --  os.findlib("alica_dummy_proxy"), 
   --  os.findlib("system_config"),
   --  os.findlib("fsystem"),
   --  os.findlib("system_util"),
   --  os.findlib("event_handling"),
   --  os.findlib("agent_id"),
   --  os.findlib("yaml-cpp"),
   --  os.findlib("gtest")
   -- }

   includedirs { 
      "alica_engine/include", 
      "alica_solver_interface/include" ,
      "alica_solver_interface/include/**" ,
      "alica_simple_solver/include" ,
      "alica_common_config/include" ,
      "alica_dummy_proxy/include" ,
      --"alica_tests/include" ,
      --"alica_tests/autogenerated/include" ,
      "../essentials/id_manager/include" , 
      "../essentials/system_config/include" , 
      "../essentials/fsystem/include" ,
      "../essentials/event_handling/include" ,
      "../dynamic-role-assignment/include",
     "../yaml-cpp/include" ,
     "../googletest/googletest/include"
   }

   files {
      "alica_engine/include/**.h", 
      "alica_engine/src/**.cpp", 
   }
   --files {"alica_engine/**", "**.h", "**.cpp" }

   excludes {
      "alica_engine/alica_tests/**",
      "alica_tests/**"
   }
   -- linkoptions {"-pthread", "-lsfml-graphics", "-lsfml-window", "-lsfml-system" }
       
   --filter "files:**.png"
   --   buildaction "Copy"

   defines { "ALICA_DEBUG_ENABLED" }

   filter "configurations:Debug"
      defines { "DEBUG", "ALICA_DEBUG_ENABLED" }
      symbols "On"

   filter "configurations:Release"
      defines { "NDEBUG" }
      optimize "On"

   dofile("alica_engine/premake5.lua") 
   dofile("alica_solver_interface/premake5.lua") 
   --dofile("alica_simple_solver/premake5.lua") 
   dofile("alica_common_config/premake5.lua") 
   --dofile("alica_dummy_proxy/premake5.lua") 
   dofile("../essentials/fsystem/premake5.lua") 
   dofile("../essentials/id_manager/premake5.lua") 
   dofile("../essentials/system_config/premake5.lua") 
   dofile("../essentials/event_handling/premake5.lua") 
   dofile("../dynamic-role-assignment/premake5.lua") 
   --dofile("../yaml-cpp/premake5.lua") 
   
--    postbuildcommands { "cp grid_sim/textures/*.* bin/Debug/textures/" }
--    postbuildmessage "Copying dependencies..."
--    os.copyfile("/textures", "%{targetdir}/textures")

-- if _ACTION == "clean" then
--		os.rmdir("bin")
--		os.rmdir("build")
-- end


