# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  alica_config = debug
  alica_engine_config = debug
  alica_solver_interface_config = debug
  dynamic_role_assignment_config = debug

else ifeq ($(config),release)
  alica_config = release
  alica_engine_config = release
  alica_solver_interface_config = release
  dynamic_role_assignment_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := alica alica_engine alica_solver_interface dynamic_role_assignment

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

alica:
ifneq (,$(alica_config))
	@echo "==== Building alica ($(alica_config)) ===="
	@${MAKE} --no-print-directory -C . -f alica.make config=$(alica_config)
endif

alica_engine:
ifneq (,$(alica_engine_config))
	@echo "==== Building alica_engine ($(alica_engine_config)) ===="
	@${MAKE} --no-print-directory -C alica_engine -f Makefile config=$(alica_engine_config)
endif

alica_solver_interface:
ifneq (,$(alica_solver_interface_config))
	@echo "==== Building alica_solver_interface ($(alica_solver_interface_config)) ===="
	@${MAKE} --no-print-directory -C alica_solver_interface -f Makefile config=$(alica_solver_interface_config)
endif

dynamic_role_assignment:
ifneq (,$(dynamic_role_assignment_config))
	@echo "==== Building dynamic_role_assignment ($(dynamic_role_assignment_config)) ===="
	@${MAKE} --no-print-directory -C ../dynamic-role-assignment -f Makefile config=$(dynamic_role_assignment_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f alica.make clean
	@${MAKE} --no-print-directory -C alica_engine -f Makefile clean
	@${MAKE} --no-print-directory -C alica_solver_interface -f Makefile clean
	@${MAKE} --no-print-directory -C ../dynamic-role-assignment -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   alica"
	@echo "   alica_engine"
	@echo "   alica_solver_interface"
	@echo "   dynamic_role_assignment"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"