-- premake5.lua

workspace "alica"
   configurations { "Debug", "Release" }
   postbuildmessage "Copying dependencies..."
 --  postbuildcommands { "cp -R grid_sim/textures  bin/%{cfg.buildcfg}" }

 -- Turn on IDE integration
--editorintegration "On"

project "alica_engine"
   kind "StaticLib"
   language "C++"
   cppdialect "C++14"
   targetdir "bin/%{cfg.buildcfg}"

   -- libdirs { 
   --  os.findlib("alica_common_config"), 
   --  os.findlib("alica_solver_interface"), 
   --  os.findlib("alica_dummy_proxy"), 
   --  os.findlib("system_config"),
   --  os.findlib("fsystem"),
   --  os.findlib("system_util"),
   --  os.findlib("event_handling"),
   --  os.findlib("agent_id"),
   --  os.findlib("yaml-cpp"),
   --  os.findlib("gtest")
   -- }

   linkoptions { 
      "../alica_solver_interface/bin/Debug/libalica_solver_interface.a", 
      "../alica_common_config/bin/Debug/libalica_common_config.a",
      "../../dynamic-role-assignment/bin/Debug/libdynamic-role-assignment.a", 
      "../../essentials/id_manager/bin/Debug/libid_manager.a",
      "../../essentials/system_config/bin/Debug/libsystem_config.a",
      "../../essentials/fsystem/bin/Debug/libfsystem.a",
      "../../essentials/event_handling/bin/Debug/libevent_handling.a",
      "../../yaml-cpp/build/libyaml-cpp.a",
      "uuid" 
   }

   includedirs { 
      "include", 
      "../alica_solver_interface/include" ,
      "../alica_common_config/include" ,
      "../../dynamic-role-assignment/include" ,
      "../../essentials/id_manager/include" , 
      "../../essentials/system_config/include" , 
      "../../essentials/fsystem/include" ,
      "../../essentials/event_handling/include" ,
      
      "../../yaml-cpp/include" ,
      
      --"../alica_solver_interface/include/**" ,
      --"alica_simple_solver/include" ,
      --"alica_dummy_proxy/include" ,

      --"../../googletest/googletest/include"
      --"alica_tests/include" ,
      --"alica_tests/autogenerated/include" ,
   }

   files {
      "include/**.h", 
      "src/**.cpp", 
   }

   excludes {
      "alica_tests/**",
   }
   -- linkoptions {"-pthread", "-lsfml-graphics", "-lsfml-window", "-lsfml-system" }
       
   --filter "files:**.png"
   --   buildaction "Copy"

   filter "configurations:Debug"
      defines { "DEBUG" }
      symbols "On"

   filter "configurations:Release"
      defines { "NDEBUG" }
      optimize "On"
    
--    postbuildcommands { "cp grid_sim/textures/*.* bin/Debug/textures/" }
--    postbuildmessage "Copying dependencies..."
--    os.copyfile("/textures", "%{targetdir}/textures")

-- if _ACTION == "clean" then
--		os.rmdir("bin")
--		os.rmdir("build")
-- end


-- dofile("RGBDriver/premake5.lua")
-- dofile("RGBEffectLibrary/premake5.lua")
-- dofile("RGBController/premake5.lua")
-- dofile("RGBQtConfig/premake5.lua")
-- dofile("RGBDaemon/premake5.lua")
-- dofile("RGBTranslation/premake5.lua")
-- dofile("RGBTests/premake5.lua")


